#!/usr/bin/env bash

# Watches code and serves interpreter version. Responds quickly to
# changes in source code. It is a bit flakey, tough. Will sometimes
# get stuck with a bogus error message no matter what the source code
# actually says. I don't know where the issue stems from, but suspect
# ghcid is having some trouble.
#
# This is the bogus error:
#
#     <interactive>:42:53-56: error:
#         • Variable not in scope: main :: IO a0
#         • Perhaps you meant ‘min’ (imported from Prelude)
#
#     ...done
#

make webclient-dev
